# Site settings
title: Deep Learning Book

url: "https://ilguyi.github.io"
github_url: "https://github.com/ilguyi/dlbook"
github_editurl: '/blob/gh-pages'
github_profile: 'https://github.com/ilguyi'
baseurl: '/dlbook'

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
mathjax: true
disqus_shortname: 'mindbox'
